[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.19.0"
eframe = "0.19.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"

[profile.release]
opt-level = 2 # fast and small wasm
